name: Deploy Release Build

on:
  push:
    branches:
      - main # Customize this branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release Build to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease
        env:
          APP_DISTRIBUTION_TOKEN: ${{ secrets.APP_DISTRIBUTION_TOKEN }}
